global:
  scrape_interval: 1s # Make scrape interval to 1s for testing.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'my_app1'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.50.207:8080']